Add make clean & rustup update to dev docs (#927)
* Add make clean to dev docs

As mentioned [here](https://github.com/dib-lab/sourmash/issues/926) update developer docs for `ImportError: cannot import name 'to_bytes'`.